spring.application.name=springboot

server.port=8081

server.servlet.context-path=/springboot-api

logging.level.root=INFO;
logging.level.com.compunet.springboot=DEBUG
logging.file.name=logs/application.log


#======================================================

# 2. ALTERNATIVA: BASE DE DATOS H2 (En Memoria o Archivo)
# ==========================================
# Driver oficial para H2 Database
spring.datasource.driver-class-name=org.h2.Driver

# Opción A: H2 en Memoria RAM
spring.datasource.url=jdbc:h2:mem:sistema-academico;DB_CLOSE_DELAY=-1

# Credenciales por defecto en H2
spring.datasource.username=user
spring.datasource.password=password

# Dialecto de Hibernate para optimizar las consultas SQL generadas hacia H2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect


# ==========================================
# 3. GESTIÓN DE ESQUEMA CON HIBERNATE (ddl-auto)
# ==========================================
# Define la estrategia de generación automática del esquema DDL:
# - none: No realiza ninguna modificación en la BD.
# - validate: Valida que las tablas coincidan con las entidades JPA (falla si hay diferencias).
# - update: Actualiza la estructura de la base de datos agregando nuevas columnas o tablas sin borrar datos.
# - create: Crea el esquema al iniciar, borrando tablas previas si existían.
# - create-drop: Crea el esquema al iniciar la app y lo destruye completamente al cerrar la aplicación.
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.encoding=UTF-8

# ==========================================
# 4. INICIALIZACIÓN DE DATOS CON SCRIPTS SQL
# ==========================================
# Define cuándo deben ejecutarse los archivos schema.sql y data.sql:
# - always: Ejecuta los scripts SQL siempre durante el arranque.
# - never: Nunca ejecuta scripts SQL automáticos.
spring.sql.init.mode=always

# Muestra u oculta las sentencias SQL ejecutadas por Hibernate en la consola de logs
spring.jpa.show-sql=false

# Diferimiento de la inicialización del DataSource:
# Esta propiedad es fundamental. Al estar en 'true', fuerza a que Spring Boot espere a que Hibernate
# termine de crear las tablas (ddl-auto) ANTES de intentar ejecutar el archivo data.sql.
spring.jpa.defer-datasource-initialization=true


# ==========================================
# 5. CONSOLA WEB DE H2
# ==========================================
# Habilita la interfaz web interactiva para inspeccionar la base de datos H2 desde el navegador
spring.h2.console.enabled=true

# Ruta URI para ingresar a la consola de H2 (ejemplo: http://localhost:8080/h2-console)
spring.h2.console.path=/h2-console